YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "flatworld.Flatworld",
        "flatworld.MapDataManipulator",
        "flatworld.ObjectManager",
        "flatworld.Preload",
        "flatworld.UI",
        "flatworld.UIs.default",
        "flatworld.eventListeners",
        "flatworld.extensions.baseEventlisteners",
        "flatworld.extensions.hexagons.ObjectHexaTerrain",
        "flatworld.extensions.hexagons.ObjectHexaUnit",
        "flatworld.extensions.hexagons.selectHexagonObject",
        "flatworld.extensions.hexagons.setupHexagonClick",
        "flatworld.extensions.hexagons.utils",
        "flatworld.extensions.mapDrag",
        "flatworld.extensions.mapMovement",
        "flatworld.extensions.mapZoom",
        "flatworld.generalUtils.arrays",
        "flatworld.generalUtils.environmentDetections",
        "flatworld.generalUtils.polyfills",
        "flatworld.log",
        "flatworld.mapApi",
        "flatworld.mapEvents",
        "flatworld.mapStates",
        "flatworld.maplayers.MapLayer",
        "flatworld.maplayers.MapLayerParent",
        "flatworld.maplayers.MapSubcontainer",
        "flatworld.objects.ObjectSprite",
        "flatworld.objects.ObjectSpriteTerrain",
        "flatworld.objects.ObjectSpriteUnit",
        "flatworld.utils.Quadtree",
        "flatworld.utils.dataManipulation",
        "flatworld.utils.effects",
        "flatworld.utils.environment",
        "flatworld.utils.general",
        "flatworld.utils.mouse",
        "flatworld.utils.resize"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});